resources:
  - name: pcf-automation-tasks
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      endpoint: ((s3_endpoint))
      bucket: ((s3_buckets))
      regexp: .*tasks-(.*).zip

  - name: pcf-automation-image
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      endpoint: ((s3_endpoint))
      bucket: ((s3_buckets))
      regexp: .*image-(.*).tgz
      
  - name: splunk-stemcell
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      endpoint: ((s3_endpoint))
      bucket: ((s3_buckets))
      regexp: bosh-stemcell-(97.*)-vsphere.*\.tgz

  # configurations
  - name: configuration
    type: git
    source:
      private_key: ((pcf-automation-ssh-key_private_key))
      uri: ((configuration_uri))
      branch: master

  - name: variable
    type: git
    source:
      private_key: ((pcf-automation-ssh-key_private_key))
      uri: ((configuration_uri))
      branch: master

jobs:
  - name: upload-stemcells
    serial: true
    plan:
      - aggregate:
          - get: pcf-automation-image
            params:
              unpack: true
          - get: pcf-automation-tasks
            params:
              unpack: true
          - get: configuration
          - get: splunk-stemcell
            trigger: true
      - task: upload-splunk-stemcell
        image: pcf-automation-image
        file: PlatformAutomation/upload-stemcell.sh
        params:
          ENV_FILE: env.yml

  - name: apply-stemcell-updates
    serial: true
    plan:
      - aggregate:
          - get: pcf-automation-image
            params:
              unpack: true
            passed:
              - upload-stemcells
            trigger: true
          - get: pcf-automation-tasks
            params:
              unpack: true
          - get: configuration
      - task: apply-product-changes
        image: pcf-automation-image
        file: PlatformAutomation/apply-changes.sh
        params:
          ENV_FILE: env.yml
