resources:
  - name: pcf-automation-tasks
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      endpoint: ((s3_endpoint))
      bucket: ((s3_buckets))
      regexp: .*tasks-(.*).zip

  - name: pcf-automation-image
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      endpoint: ((s3_endpoint))
      bucket: ((s3_buckets))
      regexp: .*image-(.*).tgz
      
  - name: splunk-stemcell
    type: s3
    source:
      access_key_id: ((s3_access_key_id))
      secret_access_key: ((s3_secret_access_key))
      region_name: ((s3_region_name))
      endpoint: ((s3_endpoint))
      bucket: ((s3_buckets))
      regexp: bosh-stemcell-(97.*)-vsphere.*\.tgz

jobs:
  - name: upload-stemcells
    serial: true
    plan:
      - aggregate:
          - get: pcf-automation-image
            params:
              unpack: true
          - get: pcf-automation-tasks
            params:
              unpack: true
          - get: splunk-stemcell
            trigger: true
      - task: upload-splunk-stemcell
        image: pcf-automation-image
        file: pcf-automation-tasks/tasks/upload-stemcell.yml
        input_mapping:
          env: env-int
          stemcell: splunk-stemcell
        params:
          ENV_FILE: env.yml

  - name: apply-stemcell-updates
    serial: true
    plan:
      - aggregate:
          - get: pcf-automation-image
            params:
              unpack: true
            passed:
              - upload-stemcells
            trigger: true
          - get: pcf-automation-tasks
            params:
              unpack: true
      - task: apply-product-changes
        image: pcf-automation-image
        file: pcf-automation-tasks/tasks/apply-changes.yml
        input_mapping:
          env: env-int
        params:
          ENV_FILE: env.yml
